#!/usr/bin/env python3
"""Freeze the non-executable source-union compact sentinel identity."""

# pyright: reportUnknownArgumentType=false
# pyright: reportUnknownVariableType=false

from __future__ import annotations

import argparse
import hashlib
import json
import runpy
from pathlib import Path
from typing import Any

from hebog.validation.external_runners import canonical_sha256, file_sha256

_ROOT = Path(__file__).parents[2]
_MANIFEST = Path(
    "config/contracts/"
    "phase-5-compact-held-out-source-union-sentinel-manifest.json"
)
_IMPLEMENTATION = Path(
    "config/contracts/"
    "phase-5-compact-held-out-source-union-sentinel-implementation-decision.json"
)
_IDENTITY = Path(
    "config/contracts/"
    "phase-5-compact-held-out-source-union-sentinel-identity-review.json"
)
_ROOT_CAUSE_REVIEW = Path(
    "config/contracts/phase-5-compact-held-out-sentinel-root-cause-pre-review.json"
)
_ROOT_CAUSE_REVIEW_SHA256 = (
    "f94d0455be9bbb4472b7ee6e6b0cd24fbf4ecc8be1d3e8a293d4467dbc02cad3"
)
_ADAPTER_REVIEW = Path(
    "config/contracts/"
    "phase-5-compact-held-out-sentinel-source-union-adapter-pre-review.json"
)
_ADAPTER_REVIEW_SHA256 = (
    "02b46ecaeb3d8bfee5f2b3d0ee37b44b5f9add2122707d2677c0a77e784c4d5c"
)
_PROGRAM_PATHS = {
    "aligned_evaluator": (
        "scripts/validation/"
        "evaluate_phase5_compact_held_out_sentinel_aligned.py"
    ),
    "alignment": "scripts/validation/compact_sentinel_alignment.py",
    "frozen_parent_evaluator": (
        "scripts/validation/evaluate_phase5_compact_held_out_sentinel.py"
    ),
    "freezer": (
        "scripts/validation/"
        "freeze_phase5_compact_held_out_source_union_sentinel.py"
    ),
    "historical_runner_helpers": (
        "scripts/benchmark/run_phase5_compact_held_out_sentinel.py"
    ),
    "population": (
        "scripts/validation/phase5_compact_held_out_source_union_sentinel.py"
    ),
    "public_facade": "src/hebog/public_api.py",
    "public_runner_identity": (
        "scripts/benchmark/run_phase5_public_finder_hebog.py"
    ),
    "source_union_adapters": (
        "scripts/validation/compact_sentinel_source_unions.py"
    ),
    "source_union_pybdsf_child": (
        "scripts/benchmark/run_phase5_compact_held_out_source_union_pybdsf.py"
    ),
    "source_union_runner": (
        "scripts/benchmark/"
        "run_phase5_compact_held_out_source_union_sentinel.py"
    ),
    "truth_compiler": (
        "scripts/validation/compile_phase5_compact_held_out_sentinel.py"
    ),
}
_FIXTURE_PATHS = {
    "alignment": (
        "tests/unit/validation/test_compact_sentinel_evaluator_alignment.py"
    ),
    "source_union_adapters": (
        "tests/unit/validation/test_compact_sentinel_source_union_adapters.py"
    ),
    "successor_tooling": (
        "tests/unit/validation/"
        "test_phase5_compact_held_out_source_union_sentinel.py"
    ),
}
_CANDIDATE = {
    "configuration_sha256": (
        "2c907949d2b9678b2d1f4cc00f8ba6c079e866842edea6873f981dc1264ed11d"
    ),
    "entrypoint": "hebog.find_sources",
    "revision": "95cfc76ded56556dc3ad6894410962d34f0d5604",
    "source_tree_sha256": (
        "8da21e86afc5035da0704724a9d29104ea8b0e4d55fa4a98f0c5f3efca9a75a5"
    ),
}
_PYBDSF = {
    "container_digest": (
        "sha256:5310afe78c8fc09ed99ddee1c6978e5e32181b69f1d22432a02ef6e3a6761198"
    ),
    "dependency_inventory_sha256": (
        "8211043e9fca55d706d1e890e2bf0b630e228a854db0949258c498506975669f"
    ),
    "finder_id": "released-pybdsf",
    "image_id": (
        "43a6513865a597285dc1bf473e27fc69fdd86fb143c35a24144eb6c1152bb36e"
    ),
    "version": "1.14.1",
}


def _json_bytes(value: object) -> bytes:
    """Return exact checked-in JSON presentation bytes."""
    return (
        json.dumps(value, allow_nan=False, indent=2, sort_keys=True) + "\n"
    ).encode()


def _bytes_sha256(value: bytes) -> str:
    """Hash generated bytes before any output is opened."""
    return hashlib.sha256(value).hexdigest()


def _bindings(root: Path, paths: dict[str, str]) -> dict[str, object]:
    """Bind each exact program or fixture file by content."""
    return {
        name: {"path": path, "sha256": file_sha256(root / path)}
        for name, path in sorted(paths.items())
    }


def _population_program(root: Path) -> dict[str, Any]:
    """Load the metadata-only population without invoking its CLI."""
    return runpy.run_path(str(root / _PROGRAM_PATHS["population"]))


def _verified_reviews(root: Path) -> dict[str, object]:
    """Require both approved prospective reviews byte for byte."""
    reviews = {
        "root_cause": (_ROOT_CAUSE_REVIEW, _ROOT_CAUSE_REVIEW_SHA256),
        "source_union_adapters": (_ADAPTER_REVIEW, _ADAPTER_REVIEW_SHA256),
    }
    for path, digest in reviews.values():
        if file_sha256(root / path) != digest:
            raise ValueError("compact sentinel approved review changed")
    return {
        name: {"path": path.as_posix(), "sha256": digest}
        for name, (path, digest) in reviews.items()
    }


def build_records(
    root: Path,
) -> tuple[bytes, dict[str, object], dict[str, object]]:
    """Build the complete prospective record set after validation."""
    reviews = _verified_reviews(root)
    program = _population_program(root)
    manifest = program["build_manifest"]()
    seed_audit = program["audit_manifest"](root, manifest)
    manifest_bytes = program["manifest_json_bytes"](manifest)
    manifest_sha256 = _bytes_sha256(manifest_bytes)
    programs = _bindings(root, _PROGRAM_PATHS)
    fixtures = _bindings(root, _FIXTURE_PATHS)
    expected_execution: dict[str, object] = {
        "dask_scheduler_address_present": True,
        "identity_review": _IDENTITY.as_posix(),
        "manifest": _MANIFEST.as_posix(),
        "output": (
            "benchmark-results/phase-5/"
            "compact-held-out-source-union-sentinel.json"
        ),
        "scratch": (
            "/private/tmp/hebog-phase5-compact-held-out-source-union-sentinel"
        ),
        "workers": 2,
    }
    implementation: dict[str, object] = {
        "implementation_id": (
            "phase-5-compact-held-out-source-union-sentinel-"
            "implementation-decision"
        ),
        "status": "implemented-and-validated-non-executable",
        "approved_reviews": reviews,
        "candidate": _CANDIDATE,
        "comparator": _PYBDSF,
        "evidence_schema_version": 3,
        "fixture_bindings": fixtures,
        "manifest": {"path": _MANIFEST.as_posix(), "sha256": manifest_sha256},
        "no_write_validation": {
            "finder_execution_started": False,
            "image_generation_started": False,
            "seed_audit": seed_audit,
            "status": "pass",
        },
        "program_bindings": programs,
        "scientific_policy": {
            "absolute_objectives": "report-only",
            "binding_catalogue_level": "source",
            "binding_topology_domain": "source-union",
            "cell_level_released_pybdsf_parity_required": True,
            "component_metrics": "diagnostic-only",
            "fitless_pybdsf_islands": "binary-support-only",
            "pooling_across_cells": False,
            "post_result_tuning_or_rescoring_allowed": False,
        },
    }
    implementation_sha256 = _bytes_sha256(_json_bytes(implementation))
    authorization = dict.fromkeys(
        (
            "another_replay",
            "current_hebog_execution",
            "cutover",
            "existing_dask_comparison",
            "held_out_execution",
            "optimization",
            "release",
            "released_pybdsf_execution",
            "rescoring",
            "tuning",
            "viewed_data_execution",
        ),
        False,
    )
    identity: dict[str, object] = {
        "identity_review_id": (
            "phase-5-compact-held-out-source-union-sentinel-identity-review"
        ),
        "status": "frozen-non-executable",
        "approved_reviews": reviews,
        "authorization": authorization,
        "candidate": _CANDIDATE,
        "comparator": _PYBDSF,
        "evidence_schema_version": 3,
        "execution_contract": {
            "caller_owned_dask_comparisons": 12,
            "current_hebog_serial_executions": 168,
            "released_pybdsf_executions": 168,
            "total_finder_executions": 348,
            "worker_concurrency": 2,
            "write_once_output": expected_execution["output"],
        },
        "expected_execution": expected_execution,
        "expected_execution_sha256": canonical_sha256(expected_execution),
        "fixture_bindings": fixtures,
        "implementation": {
            "path": _IMPLEMENTATION.as_posix(),
            "sha256": implementation_sha256,
        },
        "manifest": {"path": _MANIFEST.as_posix(), "sha256": manifest_sha256},
        "population": {
            "cell_count": 42,
            "image_count": 168,
            "role": "qualification",
            "seed_audit": seed_audit,
        },
        "program_bindings": programs,
    }
    return manifest_bytes, implementation, identity


def _write(path: Path, payload: bytes) -> None:
    """Write one new immutable record without overwrite."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("xb") as stream:
        stream.write(payload)


def freeze_records(arguments: argparse.Namespace) -> None:
    """Validate all targets before publishing the identity set."""
    root = arguments.repository_root.resolve()
    output_root = arguments.output_root.resolve()
    manifest, implementation, identity = build_records(root)
    records = (
        (_MANIFEST, manifest),
        (_IMPLEMENTATION, _json_bytes(implementation)),
        (_IDENTITY, _json_bytes(identity)),
    )
    for relative, _payload in records:
        target = output_root / relative
        if target.exists():
            raise FileExistsError(f"refusing to overwrite {target}")
    for relative, payload in records:
        _write(output_root / relative, payload)


def _parse_args() -> argparse.Namespace:
    """Parse source and output repository roots."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repository-root", type=Path, default=_ROOT)
    parser.add_argument("--output-root", type=Path, default=_ROOT)
    return parser.parse_args()


def main() -> None:
    """Freeze the exact non-executable record set."""
    freeze_records(_parse_args())


if __name__ == "__main__":
    main()
